name: ml4fl_py38
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- conda-forge::gdal>=3.1
- conda-forge::ipython
- conda-forge::ipykernel
- conda-forge::libgdal>=3.1
- pandas==1.2.3
- conda-forge::geopandas==0.9
- conda-forge::rasterio
- pip
- pip:
  # PYTORCH ECOSYSTEM
  - torch
  - torchvision
  - pytorch-lightning
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - fastprogress
  - tqdm
  - black
  - isort
  - mypy
  - opencv-python
  - google-cloud-storage
  - pyprojroot
  - Flask
  - Flask-HTTPAuth
  - Flask-Login
  - Flask-WTF
  - gunicorn
  - mercantile
  - pillow
  - pytest
  - flake8
  - s2cloudless
  - requests_html
  - gcsfs
  - fsspec
  - earthengine-api
  - geemap
  # from bug  in GEE, see https://github.com/google/earthengine-api/issues/157
  - google-api-python-client==1.12.8 
  - corner
  # documentation
  - jupyter-book
  - ghp-import