#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Ml4Floods  # The title of the book. Will be placed in the left navbar.
author                      : spaceml  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
# logo                        : book.png  # A path to the book logo
execute:
  execute_notebooks: cache